### ISSUE TITLE
Fix Visualization: Inspect Node & Inspect Overall Management

### ISSUE THREAD

**Issue by amtsvch** [DaGeRe/peass#113]
Visualization of call trees contains not-working links:

- _Inspect Node_ throws "File not found" and points to a wrong file path / file name.

- _Inspect Overall Management_ doesn't show any results.

**Comment by DaGeRe** [comment]
Thanks for the bug reports. With 6d29c6b5a4b825d765bfb31392b68f7a9d6dcaa3 and d583187393bc606f71ab01819cfe6713272aeab0, both should work now.
