### ISSUE TITLE
parameterized tests in root cause analysis

### ISSUE THREAD

**Issue by KarimAbrik** [DaGeRe/peass#114]
The execution of "getchanges" does not create suitable searchcause-commands in run-rca-$PROJECTNAME.jar for parameterized tests. I had to use java -jar to start the starter instead of ./peass and add the parameters manually in order to begin the root cause analysis.

**Comment by DaGeRe** [comment]
This should start working with https://github.com/DaGeRe/peass/commit/19fa4e3feca70607acbc0f4db99ec92bbcaa7bfe, can you confirm this?

**Comment by KarimAbrik** [comment]
Yes, now it works. Thanks!
