### ISSUE TITLE
TwiceExecutableChecker NPE

### ISSUE THREAD

**Issue by amtsvch** [DaGeRe/peass#121]
Step: _selection_.

In the Class TwiceExecutableChecker method **checkTestExistance** throws an NPE in line 61, as TempClazzFolder has been already deleted by truncateLastRunResults() in line 43.

**Comment by DaGeRe** [comment]
Could you further specify under which circumstances this happens? Since the `TwiceExecutableChecker`  works, e.g. for commons-fileupload, this cannot be a general problem.

**Comment by amtsvch** [comment]
Indeed, the issue was caused by AntTestExecutor from Peass-Ant module. 
I'll close the issue due to irrelevance here.
