### ISSUE TITLE
Testcase deserialization does not work for submodules

### ISSUE THREAD

**Issue by KarimAbrik** [DaGeRe/peass#151]
When pathing a submodule to `TestMethodCall.createFromString`, like gradoop-store/gradoop-accumulo, deserialization fails. This should be fixed.

**Comment by DaGeRe** [comment]
Thanks for the issue, this should be fixed with https://github.com/DaGeRe/peass/commit/9d1ea0a68d9342b034afdad76219a87de1c93b4c, does this work for you?

**Comment by KarimAbrik** [comment]
Yes, now it works. Thanks!
