### ISSUE TITLE
Möglichkeit bestimmte gradle tests für Androidprojekte angeben zu können

### ISSUE THREAD

**Issue by alex-iotiq** [DaGeRe/peass#22]
Da "test" task keinen "--tests" Argument akzeptiert, muss man stattdessen eine bestimmte Variante angeben wie "testDebug".
Die Möglichkeit Varianten selbst anzugeben, die ausgeführt werden sollen, wäre sinnvoll.

**Comment by DaGeRe** [comment]
Das Testgoal kann jetzt angegeben werden: https://github.com/DaGeRe/peass/blob/0bfa7aef9d6a82dd81d858330c017c30f62b6265/dependency/src/main/java/de/peass/dependency/execution/MeasurementConfigurationMixin.java#L49 Die Definition gilt dann (wenn sie erfolgt) nicht nur für Android, sondern auch für alle Projekte (so dass man bspw. tests, die mit `mvn verify` ausgeführt werden, ausführen kann.

Funktioniert das so für Dich?
