### ISSUE TITLE
Probleme mit NTFS

### ISSUE THREAD

**Issue by cathixx** [DaGeRe/peass#23]
Das Projekt lässt sich auf dem NTFS Dateisystem leider nicht bauen, da einige Dateipfade zu lang sind und einige Dateinamen enthalten nicht erlaubte zeichen. Kann man das anpassen?

Folgende Zeichen sind in Dateinamen und Verzeichnissen nicht erlaubt: \ / : * ? " < > |

`error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/946e4318267b56838aa35da0a2a4e5c0528bfe04/test_TestMe_0_946e4318267b56838aa35da0a2a4e5c0528bfe04.xml: Filename too long
error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/946e4318267b56838aa35da0a2a4e5c0528bfe04/test_TestMe_1_946e4318267b56838aa35da0a2a4e5c0528bfe04.xml: Filename too long
error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/946e4318267b56838aa35da0a2a4e5c0528bfe04/test_TestMe_2_946e4318267b56838aa35da0a2a4e5c0528bfe04.xml: Filename too long
error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/fd79b2039667c09167c721b2823425629fad6d11/test_TestMe_0_fd79b2039667c09167c721b2823425629fad6d11.xml: Filename too long
error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/fd79b2039667c09167c721b2823425629fad6d11/test_TestMe_1_fd79b2039667c09167c721b2823425629fad6d11.xml: Filename too long
error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/fd79b2039667c09167c721b2823425629fad6d11/test_TestMe_2_fd79b2039667c09167c721b2823425629fad6d11.xml: Filename too long
error: unable to create file analysis/src/test/resources/visualization/project_test_peass/rca/archived/7675e29a368e5ac051e76c145e84c80af7ae1e88/com.example.android_example.ExampleUnitTest/test_TestMe/7675e29a368e5ac051e76c145e84c80af7ae1e88/0/test_TestMe_0_7675e29a368e5ac051e76c145e84c80af7ae1e88.xml: Filename too long
error: unable to create file analysis/src/test/resources/visualization/project_test_peass/rca/archived/7675e29a368e5ac051e76c145e84c80af7ae1e88/com.example.android_example.ExampleUnitTest/test_TestMe/7675e29a368e5ac051e76c145e84c80af7ae1e88/0/test_TestMe_1_7675e29a368e5ac051e76c145e84c80af7ae1e88.xml: Filename too long
error: unable to create file analysis/src/test/resources/visualization/project_test_peass/rca/archived/7675e29a368e5ac051e76c145e84c80af7ae1e88/com.example.android_example.ExampleUnitTest/test_TestMe/7675e29a368e5ac051e76c145e84c80af7ae1e88/0/test_TestMe_2_7675e29a368e5ac051e76c145e84c80af7ae1e88.xml: Filename too long
error: unable to create file analysis/src/test/resources/visualization/project_test_peass/rca/archived/7675e29a368e5ac051e76c145e84c80af7ae1e88/com.example.android_example.ExampleUnitTest/test_TestMe/7675e29a368e5ac051e76c145e84c80af7ae1e88~1/0/test_TestMe_0_7675e29a368e5ac051e76c145e84c80af7ae1e88~1.xml: Filename too long
error: unable to create file analysis/src/test/resources/visualization/project_test_peass/rca/archived/7675e29a368e5ac051e76c145e84c80af7ae1e88/com.example.android_example.ExampleUnitTest/test_TestMe/7675e29a368e5ac051e76c145e84c80af7ae1e88~1/0/test_TestMe_1_7675e29a368e5ac051e76c145e84c80af7ae1e88~1.xml: Filename too long
error: unable to create file analysis/src/test/resources/visualization/project_test_peass/rca/archived/7675e29a368e5ac051e76c145e84c80af7ae1e88/com.example.android_example.ExampleUnitTest/test_TestMe/7675e29a368e5ac051e76c145e84c80af7ae1e88~1/0/test_TestMe_2_7675e29a368e5ac051e76c145e84c80af7ae1e88~1.xml: Filename too long
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.AddRandomNumbers/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C0_0/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C1_0/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C1_1/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C2_0/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C2_1/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C2_2/<init>__diff.txt: Invalid argument
error: unable to create file measurement/src/test/resources/sourceChangeRCATest/properties_project_3/methods/fd2c8ddf3fa52973ee54c4db87b47bb587886200/de.peass.C2_3/<init>__diff.txt: Invalid argument`

**Comment by DaGeRe** [comment]
Danke für den Hinweis. Prinzipiell sieht das für mich so aus, als ob die Ursaceh wäre, dass / als Separator genutzt wird, aber eigentlich `File.separator` genutzt werden müsste. In https://github.com/DaGeRe/peass/commit/9fba4164af7d5d971a33bc8372fcf94e3a48eede habe ich mal begonnen, das zu ersetzen. 

Wäre es möglich, mir die Stacktraces zur Verfügung zu stellen?

**Comment by cathixx** [comment]
Der Fehler tritt bereits beim Checkout auf und stammt von git clone befehl. 
(Windows hat kein Problem damit, wenn ein / als File seperator benutzt wird.)

**Comment by DaGeRe** [comment]
Ok, ist Dir klar, woher der Anfang mit der Länge dann kommt?

> error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/946e4318267b56838aa35da0a2a4e5c0528bfe04/test_TestMe_0_946e4318267b56838aa35da0a2a4e5c0528bfe04.xml: Filename too long error: unable to create file analysis/src/test/resources/dataReading/measurementsFull/measurements/com.example.android_example.ExampleUnitTest/946e4318267b56838aa35da0a2a4e5c0528bfe04/946e4318267b56838aa35da0a2a4e5c0528bfe04/test_TestMe_1_946e4318267b56838aa35da0a2a4e5c0528bfe04.xml: Filename too long error

Laut https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations sollten Dateinamen 255 Zeichen lang sein dürfen:
> NTFS allows each path component (directory or filename) to be 255 characters long
Dort hat aber der längste Teil test_TestMe_0_946e4318267b56838aa35da0a2a4e5c0528bfe04.xml nur 99 Zeichen.

**Comment by cathixx** [comment]
Nach genauerer Betrachtung scheint das tatsächlich eine Limitierung von Windows (und nicht von NTFS) zu sein, welches eine maximale Pfadlänge von 260 Zeichen erlaubt.

https://docs.microsoft.com/de-de/windows/win32/fileio/maximum-file-path-limitation

**Comment by DaGeRe** [comment]
Danke für die Info. Um Kollissionen mit bestehenden Java-Methodennamen zu vermeiden, benutzt Peass nun () statt <> in den Dateinamen für Methodennamen (also statt `<init>` `(init)`, was die Unterscheidung von `init` möglich macht): https://github.com/DaGeRe/peass/commit/7b18e90ceac5f4c181b1613fe8ec812db1ee3882

Leider hat GitHub Actions das Longpath-Problem trotzdem: https://github.com/DaGeRe/peass/runs/2060284112?check_suite_focus=true (obwohl es eigentlich schon korrekt eingestellt sein sollte: https://github.com/actions/virtual-environments/issues/1052). Könntest Du schauen, ob bei Dir klonen jetzt möglich ist?

**Comment by cathixx** [comment]
Jep. bei mir klappt der Checkout jetzt auch. Danke.
