### ISSUE TITLE
Remove JUnit-exclusions from build.gradle

### ISSUE THREAD

**Issue by mawHBT** [DaGeRe/peass#36]
Exclusions of JUnit in a gradle buildfile cause errors, for example:

```
configurations {
    all {
        exclude group: 'junit', module: 'junit'
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}
```

Such exclusions should be removed automatically.

**Comment by DaGeRe** [comment]
Thanks for the issue, this should work with the current develop branch. Could you check this?

**Comment by mawHBT** [comment]
Checked this with 2 repositories, works for us.

**Comment by DaGeRe** [comment]
Thanks for checking!
