### ISSUE TITLE
Ignore changed XML files that cause exception

### ISSUE THREAD

**Issue by stro18** [DaGeRe/peass#52]
**Description**
`GitUtils.getClazz` returns `null` if the changed file is not a Java file (e.g. webapps/docs/changelog.xml)

This results in a NullPointerException in the constructor of `ChangedEntity`

**Temporary Solution**
Add the following code to `ChangedEntity:329`

````
if (clazzName == null) {
    continue;
}
````

**Comment by DaGeRe** [comment]
Thanks for the hint, this should changed with https://github.com/DaGeRe/peass/commit/e08519603f73b116cbc76e15dd9aa2c755afa824

The use of `continue` is discouraged under most circumstances, since it may lead to hard-to-read "spaghetti" code.
