### ISSUE TITLE
Enable semicolon-seperated parameters for includes/excludes

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass#74]
Currently to define multiple includes or excludes you need to do something like:
--include=*TestA#* --include=*TestB#*

It would be more convenient to allow the form of:
--include='*TestA#*;*TestB#*'

**Comment by DaGeRe** [comment]
Thanks for the idea, this works with https://github.com/DaGeRe/peass/commit/cbed983ec29f28767fc352d46726ab15b0d68008
